version: "3"
services:
  web_server:
    container_name: web
    restart: always
    build:
    ports:
      - "3000:3000"
    links: mongodb
  mongodb:
    container_name: my_database
    image: mongo
    ports:
      - "27017:27017"
