@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

#Get -> Data All Content
GET http://localhost:3000/api/Content HTTP/1.1

####### Get Content for id 
GET http://{{host}}/api/Content/61480101c917b5d9c67fb552
###################################################
GET http://{{host}}/api/ContentwithCategory/61594325efb666001ed2fde8
###

POST http://localhost:3000/api/Content HTTP/1.1
Content-Type: {{contentType}}

{
    "title_content": "Titulo de prueba",
    "subtitle_content":"Content Subtitle", 
    "Content_text":"loremasdasdasdasdasd",
    "category":"614035487acab0df16f7cb85"
}

#####################################################

# Create Categoria

POST http://{{host}}/api/Categories
Content-Type: {{contentType}}

{
    "name": "Musica"
}

#### GET CATEGORIAS 
GET http://{{host}}/api/Categories

### Get Categories for id 
GET http://{{host}}/api/Categories/614035427acab0df16f7cb83


### 
GET http://{{host}}/api/Categories?name=Noticias